name: Covid-SpiNGS-Pipeline

on:
  push:
    branches:
    - developmentxyz


jobs:
  run-job:
    name: run pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: curl -s https://get.nextflow.io | bash 
    - run: chmod 777 nextflow
    - run: ./nextflow run setup_sim.nf

    
  

