name: Covid-SpiNGS-Pipeline

on:
  push:
    branches:
    - development


jobs:
  run-job:
    name: run pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      - id: step1
        run: ls -la
  

