name: Covid-SpiNGS-Pipeline

on:
  push:
    branches:
    - development


jobs:
  run-job:
    name: run pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls -la
    - run: java -version
    - run: curl -s https://get.nextflow.io | bash && chmod +x nextflow
    - run: nextflow run_pipeline.nf
    
  

